### ISSUE TITLE
Build and release a new version of the OpenBSD box

### ISSUE THREAD

**Issue by dentarg** [twingly/boxes#15]
We want a box with the fix for https://github.com/twingly/boxes/issues/5 (https://github.com/twingly/boxes/commit/c40f64f2ddfb84fd3f77577882309410d7e8cc05).

**Comment by dentarg** [comment]
When #19 is merged and released to Vagrant Cloud we can close this one I think.

**Comment by jage** [comment]
New box built and released: https://app.vagrantup.com/twingly/boxes/openbsd-6.2-amd64/versions/1.0.1
