### ISSUE TITLE
OpenBSD 6.6

### ISSUE THREAD

**Issue by dentarg** [twingly/boxes#25]
https://marc.info/?l=openbsd-announce&m=157132045926047&w=2

**Comment by dentarg** [comment]
We should remove these lines

https://github.com/twingly/boxes/blob/2b6ffbee255322e3e1151d541cca100725c11590/openbsd/scripts/postinstall.sh#L11-L13

They shouldn't be needed and they allow for stable packages to be used: https://marc.info/?l=openbsd-announce&m=156577865917831&w=2

**Comment by roback** [comment]
We got OpenBSD 6.6 in #26, but the comment above has not been addressed yet.

**Comment by dentarg** [comment]
Oh :) I must have forgotten about that.

**Comment by dentarg** [comment]
The box was published a few days ago.

https://app.vagrantup.com/twingly/boxes/openbsd-6.6-amd64/versions/1.0.0
