### ISSUE TITLE
OpenBSD: add something clever to /etc/myname

### ISSUE THREAD

**Issue by dentarg** [twingly/boxes#5]
Because the box was built on my computer on my LAN the name is as follows. So the name will vary depending on who built the box where.

```
$ uname -a
OpenBSD openbsd58.lan.dentarg.net 5.8 GENERIC#1170 amd64
$ cat /etc/myname
openbsd58.lan.dentarg.net
```

I think we can solve it by adding something to `/etc/myname` when we building the box.

**Comment by jage** [comment]
How about just "openbsd58"?

**Comment by dentarg** [comment]
Sure, we could try that.

**Comment by jage** [comment]
Did an attempt with the following in `postinstall.sh`:

```
# ensure consistent resolvable hostname
hostname=$(hostname -s)
printf "%s\n" "$hostname" > /etc/myname
printf "127.0.0.1\tlocalhost %s\n" "$hostname" > /etc/hosts
printf "::1\t\tlocalhost %s\n" "$hostname" >> /etc/hosts
```

But it didn't work, when importing the box it had `openbsdXX.SOME.DOMAIN` in `/etc/myname`. Not sure if it's some box-cache on my machine or something I'm not understanding about the build-process.

**Comment by dentarg** [comment]
I played around a bit with `/etc/defaultdomain` (http://man.openbsd.org/defaultdomain, http://man.openbsd.org/domainname.1), but it made no difference.

But for me, the above snippet worked. `hostname` printed just "openbsd61". I'm not sure if it was difference in some cache (if there is one?), or if it now behaves different with this OpenBSD version.

**Comment by dentarg** [comment]
```
$ vagrant ssh
OpenBSD 6.1 (GENERIC) #19: Sat Apr  1 13:42:46 MDT 2017

Welcome to OpenBSD: The proactively secure Unix-like operating system.

Please use the sendbug(1) utility to report bugs in the system.
Before reporting a bug, please try to reproduce it with the latest
version of the code.  With bug reports, please try to ensure that
enough information to reproduce the problem is enclosed, and if a
known fix for it exists, include that as well.

$ uname -a
OpenBSD openbsd61 6.1 GENERIC#19 amd64
$ hostname
openbsd61
$ cat /etc/myname
openbsd61
$ cat /etc/hosts
127.0.0.1       localhost openbsd61
::1             localhost openbsd61
```

**Comment by jage** [comment]
> But for me, the above snippet worked. hostname printed just "openbsd61". I'm not sure if it was difference in some cache (if there is one?), or if it now behaves different with this OpenBSD version.

Aha, nice. Well then I guess we should add it and maybe build a new box.

**Comment by dentarg** [comment]
Yes.

This is how the box currently behaves:

```
$ uname -a
OpenBSD openbsd61.my.domain 6.1 GENERIC#19 amd64
$ hostname
openbsd61.my.domain
$ ping openbsd61
ping: no address associated with name
$ cat /etc/hosts
127.0.0.1       localhost
::1             localhost
```

**Comment by jage** [comment]
Thought I would be able to close this issue with #18 

But just noticed (after the box was released) that the hostname is `openbsd61` when I expected `openbsd62`.

```

$ vagrant ssh
Last login: Sat Dec  9 09:27:33 2017 from 10.0.2.2
OpenBSD 6.2 (GENERIC) #132: Tue Oct  3 21:18:21 MDT 2017

$ hostname
openbsd61
```

**Comment by dentarg** [comment]
Re-open this issue then?

What do you have in /etc/hosts and /etc/myame?

**Comment by jage** [comment]
> What do you have in /etc/hosts and /etc/myame?

```
$ cat /etc/hosts
127.0.0.1       localhost openbsd61
::1             localhost openbsd61
$ cat /etc/myname
openbsd61
```

**Comment by dentarg** [comment]
For me with the released box:

```
$ hostname
vagrant-openbsd

$ cat /etc/myname
vagrant-openbsd

$ cat /etc/hosts
127.0.0.1       vagrant-openbsd vagrant-openbsd
127.0.0.1       localhost openbsd61
::1             localhost openbsd61
```

**Comment by walro** [comment]
https://github.com/twingly/boxes/blob/38178fa70320b6bce76f6a418ef74f21c86fd77f/openbsd/template.json#L31 guess that is the culprit

**Comment by dentarg** [comment]
Tested https://app.vagrantup.com/twingly/boxes/openbsd-6.2-amd64/versions/1.0.1, we are good now:

```
$ hostname
vagrant-openbsd
$ cat /etc/hosts
127.0.0.1       vagrant-openbsd vagrant-openbsd
127.0.0.1       localhost openbsd62
::1             localhost openbsd62
```
