### ISSUE TITLE
Packer: Update FreeBSD box to 10.3

### ISSUE THREAD

**Issue by jage** [twingly/boxes#7]
[![Bountysource](https://api.bountysource.com/badge/issue?issue_id=33900037)](https://www.bountysource.com/issues/33900037-freebsd-10-3-box?utm_source=33900037&utm_medium=shield&utm_campaign=ISSUE_BADGE)

The FreeBSD 10.2 box should be updated to 10.3.

**Comment by walro** [comment]
Closed by #9.
